package com.mycompany.urna_eletronica;

import java.awt.Image;
import static java.lang.Thread.sleep;
import java.time.Instant;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Suricato Furtivo
 */
public class telaUrna extends javax.swing.JFrame {

    Votos cadastro = new Votos();
    Urna_eletronica app = new Urna_eletronica();
    int contOrdem = 0;
    int contEx = 1;
    Fim fim = new Fim();

    String Sen = "";
    String Gov = "";
    String Pres = "";
    boolean validado;
    boolean validConf=true;

    //como acessar os elementos de uma classe em uma lista
    //(cadastro.getEleitor().get(0).nome)
    /**
     * Creates new form telaUrna
     */
    public telaUrna() {
        initComponents();

        app.Iniciar(labSeuVoto, labCargo, numero, nomeCanditato, partido, instrucVoto, num1, num2, num3, labNome, labPartido, nomeEleitor, labEleitor, bConfirmar, fotoCand);

        //devido ao nosso projeto não está vinculado ao banco de dados, é necessário atritbuir os eleitores sempre que a urna iniciar
        ArrayList<Eleitor> listaDeEleitores = new ArrayList<>();
        Eleitor eleitor1 = new Eleitor("10", "Kevin", "-", "-", "-");
        Eleitor eleitor2 = new Eleitor("15", "Tiago", "-", "-", "-");
        Eleitor eleitor3 = new Eleitor("20", "Raphael", "-", "-", "-");
        Eleitor eleitor4 = new Eleitor("25", "Berenguer", "-", "-", "-");
        Eleitor eleitor5 = new Eleitor("30", "Wyll", "-", "-", "-");
        Eleitor eleitor6 = new Eleitor("35", "Icaro", "-", "-", "-");

        listaDeEleitores.add(eleitor1);
        listaDeEleitores.add(eleitor2);
        listaDeEleitores.add(eleitor3);
        listaDeEleitores.add(eleitor4);
        listaDeEleitores.add(eleitor5);
        listaDeEleitores.add(eleitor6);

        cadastro.setEleitor(listaDeEleitores);
        fim.setSize(520, 340);
        fim.setLocation(0, 0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        bCorrigir = new javax.swing.JButton();
        bConfirmar = new javax.swing.JButton();
        bBranco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        instrucVoto = new javax.swing.JTextArea();
        telaCandidato = new javax.swing.JPanel();
        labSeuVoto = new javax.swing.JLabel();
        labCargo = new javax.swing.JLabel();
        nomeCanditato = new javax.swing.JLabel();
        labNome = new javax.swing.JLabel();
        labPartido = new javax.swing.JLabel();
        num1 = new javax.swing.JTextField();
        num3 = new javax.swing.JTextField();
        numero = new javax.swing.JLabel();
        num2 = new javax.swing.JTextField();
        partido = new javax.swing.JLabel();
        labEleitor = new javax.swing.JLabel();
        nomeEleitor = new javax.swing.JTextField();
        fotoCand = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B1.setBackground(new java.awt.Color(0, 0, 0));
        B1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B1.setForeground(new java.awt.Color(255, 255, 255));
        B1.setText("1");
        B1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        B1.setBorderPainted(false);
        B1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(0, 0, 0));
        B2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B2.setForeground(new java.awt.Color(255, 255, 255));
        B2.setText("2");
        B2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        B2.setBorderPainted(false);
        B2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(0, 0, 0));
        B3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B3.setForeground(new java.awt.Color(255, 255, 255));
        B3.setText("3");
        B3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        B3.setBorderPainted(false);
        B3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(0, 0, 0));
        B4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B4.setForeground(new java.awt.Color(255, 255, 255));
        B4.setText("4");
        B4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        B4.setBorderPainted(false);
        B4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(0, 0, 0));
        B5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B5.setForeground(new java.awt.Color(255, 255, 255));
        B5.setText("5");
        B5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        B5.setBorderPainted(false);
        B5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setBackground(new java.awt.Color(0, 0, 0));
        B6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B6.setForeground(new java.awt.Color(255, 255, 255));
        B6.setText("6");
        B6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        B6.setBorderPainted(false);
        B6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setBackground(new java.awt.Color(0, 0, 0));
        B7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B7.setForeground(new java.awt.Color(255, 255, 255));
        B7.setText("7");
        B7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        B7.setBorderPainted(false);
        B7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B8.setBackground(new java.awt.Color(0, 0, 0));
        B8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B8.setForeground(new java.awt.Color(255, 255, 255));
        B8.setText("8");
        B8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        B8.setBorderPainted(false);
        B8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setBackground(new java.awt.Color(0, 0, 0));
        B9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B9.setForeground(new java.awt.Color(255, 255, 255));
        B9.setText("9");
        B9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        B9.setBorderPainted(false);
        B9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        B10.setBackground(new java.awt.Color(0, 0, 0));
        B10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B10.setForeground(new java.awt.Color(255, 255, 255));
        B10.setText("0");
        B10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        B10.setBorderPainted(false);
        B10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });

        bCorrigir.setBackground(new java.awt.Color(227, 123, 64));
        bCorrigir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bCorrigir.setText("CORRIGIR");
        bCorrigir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        bCorrigir.setBorderPainted(false);
        bCorrigir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCorrigir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCorrigirActionPerformed(evt);
            }
        });

        bConfirmar.setBackground(new java.awt.Color(9, 227, 85));
        bConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bConfirmar.setText("CONFIRMAR");
        bConfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        bConfirmar.setBorderPainted(false);
        bConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });

        bBranco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bBranco.setText("BRANCO");
        bBranco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        bBranco.setBorderPainted(false);
        bBranco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrancoActionPerformed(evt);
            }
        });

        instrucVoto.setEditable(false);
        instrucVoto.setColumns(20);
        instrucVoto.setRows(5);
        instrucVoto.setText("Aperte a Tecla: \n    CONFIRMAR para CONFIRMAR este voto\n    CORRIGE para REINICIAR este voto");
        jScrollPane1.setViewportView(instrucVoto);

        telaCandidato.setPreferredSize(new java.awt.Dimension(520, 340));

        labSeuVoto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labSeuVoto.setText("Seu voto para ");

        labCargo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labCargo.setText("Cargo");

        nomeCanditato.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nomeCanditato.setText("Nome:");
        nomeCanditato.setMaximumSize(new java.awt.Dimension(250, 32));

        labNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labNome.setText("labNome");

        labPartido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labPartido.setText("labPartido");

        num1.setEditable(false);

        num3.setEditable(false);
        num3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        numero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numero.setText("Número:");

        num2.setEditable(false);
        num2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        partido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        partido.setText("Partido: ");

        labEleitor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labEleitor.setText("Nº Título de Eleitor:");

        nomeEleitor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nomeEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEleitorActionPerformed(evt);
            }
        });

        fotoCand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoCand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fotoCand.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fotoCand.setOpaque(true);

        javax.swing.GroupLayout telaCandidatoLayout = new javax.swing.GroupLayout(telaCandidato);
        telaCandidato.setLayout(telaCandidatoLayout);
        telaCandidatoLayout.setHorizontalGroup(
            telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCandidatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCandidatoLayout.createSequentialGroup()
                        .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labEleitor)
                            .addGroup(telaCandidatoLayout.createSequentialGroup()
                                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(telaCandidatoLayout.createSequentialGroup()
                                .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeCanditato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(partido))
                                .addGap(18, 18, 18)
                                .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labPartido)
                                    .addComponent(labNome))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeEleitor)
                            .addGroup(telaCandidatoLayout.createSequentialGroup()
                                .addGap(0, 96, Short.MAX_VALUE)
                                .addComponent(fotoCand, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(telaCandidatoLayout.createSequentialGroup()
                        .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labSeuVoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCargo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        telaCandidatoLayout.setVerticalGroup(
            telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCandidatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labSeuVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCandidatoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeCanditato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labNome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(partido, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCandidatoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(fotoCand, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(telaCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEleitor)
                    .addComponent(nomeEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCorrigir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telaCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16)
                                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16)
                                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16)
                                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16)
                                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(telaCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bCorrigir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code
        app.digNum(num1, num2, num3, B1, contOrdem, labCargo, nomeEleitor,labNome);
        validConf = app.exibirCadidato(num1, num2, num3, contOrdem, labNome, nomeCanditato, labPartido, partido, fotoCand, instrucVoto, numero);

    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        app.digNum(num1, num2, num3, B2, contOrdem, labCargo, nomeEleitor, labNome);
        validConf = app.exibirCadidato(num1, num2, num3, contOrdem, labNome, nomeCanditato, labPartido, partido, fotoCand, instrucVoto, numero);
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        app.digNum(num1, num2, num3, B3, contOrdem, labCargo, nomeEleitor,labNome);
        validConf = app.exibirCadidato(num1, num2, num3, contOrdem, labNome, nomeCanditato, labPartido, partido, fotoCand, instrucVoto, numero);
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_B9ActionPerformed

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_B10ActionPerformed

    private void bBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBrancoActionPerformed
        // TODO add your handling code here:
        app.limpar(numero, num1, num2, num3, labNome, nomeCanditato, labPartido, partido, fotoCand, instrucVoto);
        app.VotoBranco(numero, num1, num2, num3, contOrdem, labNome, nomeCanditato, labPartido, partido, fotoCand, instrucVoto);
    }//GEN-LAST:event_bBrancoActionPerformed

    private void bCorrigirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCorrigirActionPerformed
        // TODO add your handling code here:

        if (contOrdem == 0) {
            nomeEleitor.setText("");
        }

        if (contOrdem > 0 && contOrdem < 4) {
            app.limpar(numero, num1, num2, num3, labNome, nomeCanditato, labPartido, partido, fotoCand, instrucVoto);
        }
    }//GEN-LAST:event_bCorrigirActionPerformed

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarActionPerformed
        // TODO add your handling code here:
       
        //validação do eleitor no cadastro
        if (contOrdem == 0) {
            
            for (int i = 0; i < cadastro.getEleitor().size(); i++) {
                validado = cadastro.ValidarEleitor(cadastro.getEleitor().get(i).getTitulo(), nomeEleitor);
                
            }
        }

        if (validado == true) {
            if(validConf == true){
            //validar o botão confirmar somente após a digitação dos números dos candidatos 
            //System.out.println("ELEITOR VALIDADO");
            app.quantNum(contOrdem, num3);
            if (contOrdem == 1) {
                Sen = app.GuardarCandidato(contOrdem, labNome);
            } else if (contOrdem == 2) {
                Gov = app.GuardarCandidato(contOrdem, labNome);
            } else if (contOrdem == 3) {
                Pres = app.GuardarCandidato(contOrdem, labNome);
            }

            //Salvar e Limpar
            if (contOrdem >= 1) {
                //salva votos

                //limpar votos
                app.limpar(numero, num1, num2, num3, labNome, nomeCanditato, labPartido, partido, fotoCand, instrucVoto);
            }
            //Fim dos votos
            contOrdem++;

            app.IniciarVotacao(labSeuVoto, labCargo, numero, nomeCanditato, partido, instrucVoto, num1, num2, num3, labNome, labPartido, nomeEleitor, bConfirmar, contOrdem);
            }
            if (contOrdem == 4) {
                for (int i = 0; i < cadastro.getEleitor().size(); i++) {
                    if ((nomeEleitor.getText()).equals(cadastro.getEleitor().get(i).getTitulo())) {
                        cadastro.getEleitor().get(i).setVotoSen(Sen);
                        cadastro.getEleitor().get(i).setVotoGov(Gov);
                        cadastro.getEleitor().get(i).setVotoPres(Pres);
                    }

                }

                contOrdem = app.finalizar(labSeuVoto, labCargo, numero, nomeCanditato, partido, instrucVoto, num1, num2, num3, labNome, labPartido, nomeEleitor, labEleitor, fotoCand);
                cadastro.validado = false;
                contEx++;

                try {
                    //telaCandidato.add(fim);

                    // o Sleep não está funcionando com o jpainel fim, o programa está rodando apenas uma única vez desta maneira
                    Thread.sleep(3000);
                    fim.setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(telaUrna.class.getName()).log(Level.SEVERE, null, ex);
                }

                fim.setVisible(false);
                //só vai abrir para um novo eleitor com esta linha abaixo e tirar o fim(true) e add fim
                app.Iniciar(labSeuVoto, labCargo, numero, nomeCanditato, partido, instrucVoto, num1, num2, num3, labNome, labPartido, nomeEleitor, labEleitor, bConfirmar, fotoCand);
            }

            //exibir cargo do candidato
            app.TelaCargo(labCargo, contOrdem);
        } else if(!(nomeEleitor.getText().equals("relatorio") || nomeEleitor.getText().equals("RELATORIO"))){
            System.out.println("NÃO VALIDADO");
        }
        
        //impressão dos votos
        if (nomeEleitor.getText().equals("relatorio") || nomeEleitor.getText().equals("RELATORIO")) {
            for (int i = 0; i < cadastro.getEleitor().size(); i++) {
                int cont = 0;
                if (!(cadastro.getEleitor().get(i).getVotoSen().equals("-"))) {
                    System.out.println("\nNº Título: " + cadastro.getEleitor().get(i).getTitulo());
                    System.out.println("Nome: " + cadastro.getEleitor().get(i).getNome());
                    System.out.println("Voto Senador : " + cadastro.getEleitor().get(i).getVotoSen());
                    System.out.println("Voto Governador: " + cadastro.getEleitor().get(i).getVotoGov());
                    System.out.println("Voto Presidente: " + cadastro.getEleitor().get(i).getVotoPres());
                    cont++;
                }
                if (cont == contEx) {
                    break;
                }
            }
            nomeEleitor.setText("");
        }


    }//GEN-LAST:event_bConfirmarActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num3ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num2ActionPerformed

    private void nomeEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEleitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEleitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaUrna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton bBranco;
    private javax.swing.JButton bConfirmar;
    private javax.swing.JButton bCorrigir;
    private javax.swing.JLabel fotoCand;
    private javax.swing.JTextArea instrucVoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labCargo;
    private javax.swing.JLabel labEleitor;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labPartido;
    private javax.swing.JLabel labSeuVoto;
    private javax.swing.JLabel nomeCanditato;
    private javax.swing.JTextField nomeEleitor;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField num3;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel partido;
    private javax.swing.JPanel telaCandidato;
    // End of variables declaration//GEN-END:variables

}
